### ISSUE TITLE
Horse code cannot be entered by a human

### ISSUE THREAD

**Issue by sleepypikachu** [sleepypikachu/horse-code#7]
Horse code is generated using sequences of 🐴, 🐎, and [ZWNJ](https://en.wikipedia.org/wiki/Zero-width_non-joiner) non printed characters.

This is pretty awkward for a human to enter and while my expectation is that the majority of users will not be typing in their messages using morse code it seems like a reasonable expecatation that this would work.

Proposal is to add a new set of controls for entering horses, joiners and spaces in order to allow the user to quickly compose messages (assuming they are familiar with morse code).

**Comment by magdalenapaluch** [comment]
can you assign this to me?

**Comment by sleepypikachu** [comment]
No problem @magdalenapaluch, thanks for your interest. Please note #8 which is replacing ZWNJ with space and word separator with double space. Don't mind if this PR accounts for that change or not but should be easy for me to rewire the buttons later.

Please make sure the UI changes are responsive, the mobile view is important for this application!

**Comment by magdalenapaluch** [comment]
Hi @sleepypikachu ;) 

- there's an issue when you start typing in letters and then hit the horse button. Do you have an idea what should happen then? Input clear?

![image](https://user-images.githubusercontent.com/49305201/96037678-722df680-0e66-11eb-8645-cf41ca3422c3.png)

I love the idea with horse code, I laughed sincerely, when I saw the About info. Great project man :D

**Comment by magdalenapaluch** [comment]
or maybe should I disable horse buttons while typing letters? Up until someone hits the toggle button?

**Comment by sleepypikachu** [comment]
Thanks! I think horse buttons should only be visible when the entry mode is horse code (as you say you cannot enter horses as text!). You will need 4 buttons total: short, long, end character (single space), end word (double space). Not sure how these should be named but could use some emoji if you find appropriate ones!

The space/double space behavior is new and removes the need for ZWNJ so please rebase to get the new behavior. I like the way you've drawn the buttons, they look great!

**Comment by magdalenapaluch** [comment]
Hi @sleepypikachu 

I've made a PR, I'd appreciate any feedback, constructive criticism is welcome, it's my beginning with react :)

**Comment by sleepypikachu** [comment]
Hi @magdalenapaluch, the visuals look great!

I can see why you have removed the inputRef stuff but unfortunately this makes the performance pretty woeful on mobile because it causes lots of re-draws. That's why I had to put it in in the first place. :-(

I'll pull your branch and see if I can find a different solution to the programmatic character appending. :-)
